### ISSUE TITLE
Unconfigured actions misleads users into authorization config

### ISSUE THREAD

**Issue by brkn** [bobf/active_element#4]
### Problem
Currently unconfigured actions renders this page [app/views/active_element/default_views/forbidden.html.erb](https://github.com/bobf/active_element/blob/main/app/views/active_element/default_views/forbidden.html.erb).

```
Forbidden
Access to this resource has not been configured
```

But since this is not actually related to authorization, _Forbidden_ text is misleading.

### Suggested behaviour

It should nudge user into configure the relevant action instead. An example message would look like this

```erb
<h1 class='danger'>Missing action configuration</h1>
<% if development_env? %>
	<p>Maybe you've forgotten to configure this action? </p>
	<pre>active_element.viewable_fields :your_fields</pre>
<% end %>
```

**Comment by bobf** [comment]
https://github.com/bobf/active_element/commit/738918c8a3ac0d168abb6b084706fc7107bee812#diff-637824d9fff63ac8bd35e40ec27799f3f3a889e652d36cd6e2a36f2398e24eae
